version: '3.8'

volumes:
  n8n_storage:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./:/home/node/.n8n/custom/n8n-nodes-1shot
      # - ./:/home/node/.n8n/custom/node_modules/n8n-nodes-1shot
    environment:
      - N8N_HOST=f6d9-136-24-140-230.ngrok-free.app
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://f6d9-136-24-140-230.ngrok-free.app
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      # - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom/node_modules/n8n-nodes-1shot
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom/
      - NODE_ENV=development
      - N8N_LOG_LEVEL=debug